import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Providers } from '@/components/Providers';
import { getServerSession } from 'next-auth';
import { authConfig } from './configs/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig);
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers session={session}>
          <Header />
          <>{children}</>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
