services:
  api:
    build:
      context: backend/
    container_name: backend_cafe
    restart: unless-stopped
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - ./data/:$PG_DATA
#    depends_on:
#      - db
#
#  db:
#    image: postgres:16.0-alpine3.18
#    restart: always
#    env_file:
#      - backend/.env
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./data/db:$PG_DATA

  redis:
    image: "redis:alpine"

  celery:
    build:
      context: backend/
    command: celery -A Cafe_system worker -l INFO
    depends_on:
#      - db
      - redis
      - api
    restart: on-failure
    env_file:
      - backend/.env


  frontend:
    depends_on:
      - api
    build:
      context: frontend/
    ports:
      - '3000:3000'
    container_name: frontend_cafe
    restart: unless-stopped
