# Generated by Django 5.0.6 on 2024-05-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
    ]
