# Generated by Django 5.0.6 on 2024-06-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_verification_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
