export const MetroLines = [
  {
    id: 0,
    name: 'Red line',
    slug: 'red',
  },
  {
    id: 1,
    name: 'Blue line',
    slug: 'blue',
  },
  {
    id: 2,
    name: 'Green line',
    slug: 'green',
  },
];

export const PLACELIST = [
  {
    id: 0,
    img: '/data/1.jpg',
    type: 'Ресторан',
    link: '/restoran-mamay',
    name: 'Mamay',
    comments: 16,
    rating: 1.6,
    metro: 'Лівобережна',
    address: 'Дніпровська набережна, 2',
    medium_check: 999,
  },
  {
    id: 1,
    img: '/data/2.jpg',
    type: 'Ресторан',
    link: '/restoran-la-maison',
    name: '«La Maison»',
    metro: 'Лукьяновская',
    comments: 20,
    rating: 3.9,
    address: 'Дніпровська набережна, 2',
    medium_check: 1150,
  },
  {
    id: 2,
    img: '/data/3.jpg',
    type: 'Ресторан',
    link: '/restoran-gogi-dnprovska-nab',
    name: '«Gogi Днепровская наб.»',
    metro: 'Осокорки',
    comments: 16,
    rating: 1.9,
    address: 'Дніпровська набережна, 2',
    medium_check: 1350,
  },
  {
    id: 3,
    img: '/data/4.jpg',
    type: 'Ресторан',
    link: '/restoran-porto-maltese',
    name: '«Porto Maltese (Порто Мальтезе)»',
    metro: 'Арсенальная',
    comments: 52,
    rating: 4.7,
    address: 'Дніпровська набережна, 2',
    medium_check: 1150,
  },
  {
    id: 4,
    img: '/data/5.jpg',
    type: 'Ресторан',
    link: '/restoran-porto-maltese',
    name: 'Бистро Пекаря на Тарасовской',
    metro: 'Олимпийская',
    comments: 31,
    rating: 3,
    address: 'Дніпровська набережна, 2',
    medium_check: 550,
  },
  {
    id: 5,
    img: '/data/5.jpg',
    type: 'Ресторан',
    link: '/restoran-bistro-pekarya-na-tarasovskoy',
    name: 'Бистро Пекаря на Тарасовской',
    metro: 'Олимпийская',
    comments: 31,
    rating: 3.5,
    address: 'Дніпровська набережна, 2',
    medium_check: 1599,
  },
];
export const FILTERS = {
  city: {
    ID: '1',
    SLUG: 'kyiv',
    NAME: 'Київ',
    VISIBLE: '1',
    post: null,
    post_seo: null,
  },
  vides: [
    {
      ID: '38',
      SLUG: 'banket-hall',
      NAME: 'Банкет-хол',
      PLURAL: 'банкет-холи',
      PARENTAL_CASE: 'банкет-холів',
      DATIVE: 'банкет-холі',
      post: null,
      post_seo: null,
    },
    {
      ID: '33',
      SLUG: 'bar',
      NAME: 'Бар',
      PLURAL: 'бари',
      PARENTAL_CASE: 'барів',
      DATIVE: 'барі',
      post: null,
      post_seo: null,
    },
    {
      ID: '37',
      SLUG: 'gostinichno-restorannyj-kompleks',
      NAME: 'Готельно-ресторанний комплекс',
      PLURAL: 'готельно-ресторанні комплекси',
      PARENTAL_CASE: 'готельно-ресторанних комплексів',
      DATIVE: 'готельно-ресторанном комплексі',
      post: null,
      post_seo: null,
    },
    {
      ID: '36',
      SLUG: 'kaviarnia',
      NAME: "Кав'ярня",
      PLURAL: 'кофейні',
      PARENTAL_CASE: 'кофейнь',
      DATIVE: 'кофейні',
      post: null,
      post_seo: null,
    },
    {
      ID: '31',
      SLUG: 'cafe',
      NAME: 'Кафе',
      PLURAL: 'кафе',
      PARENTAL_CASE: 'кафе',
      DATIVE: 'кафе',
      post: null,
      post_seo: null,
    },
    {
      ID: '34',
      SLUG: 'piceria',
      NAME: 'Піцерія',
      PLURAL: 'піцерії',
      PARENTAL_CASE: 'піцерій',
      DATIVE: 'піцерії',
      post: null,
      post_seo: null,
    },
    {
      ID: '32',
      SLUG: 'paby',
      NAME: 'Паб',
      PLURAL: 'паби',
      PARENTAL_CASE: 'пабів',
      DATIVE: 'пабі',
      post: null,
      post_seo: null,
    },
    {
      ID: '39',
      SLUG: 'plyazhniy-kompleks',
      NAME: 'Пляжний комплекс',
      PLURAL: 'пляжні комплекси',
      PARENTAL_CASE: 'пляжних комплексів',
      DATIVE: 'пляжному комплексі',
      post: null,
      post_seo: null,
    },
    {
      ID: '30',
      SLUG: 'restorany',
      NAME: 'Ресторан',
      PLURAL: 'ресторани',
      PARENTAL_CASE: 'ресторанів',
      DATIVE: 'ресторані',
      post: null,
      post_seo: null,
    },
    {
      ID: '35',
      SLUG: 'trattoria',
      NAME: 'Тратторія',
      PLURAL: 'тратторії',
      PARENTAL_CASE: 'тратторій',
      DATIVE: 'тратторії',
      post: null,
      post_seo: null,
    },
  ],
  cuisine: [
    {
      ID: '30',
      post: null,
      _NAME: 'Авторська',
      SLUG: 'avtorskaja',
      post_seo: null,
    },
    {
      ID: '34',
      post: null,
      _NAME: 'Азербайджанська',
      SLUG: 'aizerbaizanskaja',
      post_seo: null,
    },
    {
      ID: '4',
      post: null,
      _NAME: 'Азіатська',
      SLUG: 'aziatskaja',
      post_seo: null,
    },
    {
      ID: '5',
      post: null,
      _NAME: 'Американська',
      SLUG: 'amerikanskaja',
      post_seo: null,
    },
    {
      ID: '45',
      post: null,
      _NAME: 'Афганська',
      SLUG: 'afganskaya',
      post_seo: null,
    },
    {
      ID: '51',
      post: null,
      _NAME: 'Балканська',
      SLUG: 'balkanskaya',
      post_seo: null,
    },
    {
      ID: '46',
      post: null,
      _NAME: 'Бельгійська',
      SLUG: 'belgiyskaya',
      post_seo: null,
    },
    {
      ID: '29',
      post: null,
      _NAME: 'Бразильська',
      SLUG: 'brasilskaja',
      post_seo: null,
    },
    {
      ID: '39',
      post: null,
      _NAME: 'Бургери',
      SLUG: 'burgeri',
      post_seo: null,
    },
    {
      ID: '38',
      post: null,
      _NAME: 'Буріто',
      SLUG: 'burrito',
      post_seo: null,
    },
    {
      ID: '49',
      post: null,
      _NAME: "В'єтнамська",
      SLUG: 'vyetnamskaya',
      post_seo: null,
    },
    {
      ID: '7',
      post: null,
      _NAME: 'Вегетаріанська',
      SLUG: 'vegeterianskaja',
      post_seo: null,
    },
    {
      ID: '6',
      post: null,
      _NAME: 'Вірменська',
      SLUG: 'armanskaja',
      post_seo: null,
    },
    {
      ID: '31',
      post: null,
      _NAME: 'Грецька',
      SLUG: 'greczaskaja',
      post_seo: null,
    },
    {
      ID: '8',
      post: null,
      _NAME: 'Грузинська',
      SLUG: 'gruzinskaja',
      post_seo: null,
    },
    {
      ID: '9',
      post: null,
      _NAME: 'Домашня',
      SLUG: 'domasniaja',
      post_seo: null,
    },
    {
      ID: '41',
      post: null,
      _NAME: 'Ефіопська',
      SLUG: 'efiopskaja',
      post_seo: null,
    },
    {
      ID: '32',
      post: null,
      _NAME: 'Єврейська',
      SLUG: 'evrejskaja',
      post_seo: null,
    },
    {
      ID: '10',
      post: null,
      _NAME: 'Європейська',
      SLUG: 'evropejskaja',
      post_seo: null,
    },
    {
      ID: '53',
      post: null,
      _NAME: 'Індійська',
      SLUG: 'indian',
      post_seo: null,
    },
    {
      ID: '44',
      post: null,
      _NAME: 'Інтернаціональна',
      SLUG: 'intarnacjonalnaja',
      post_seo: null,
    },
    {
      ID: '24',
      post: null,
      _NAME: 'Ірландська',
      SLUG: 'irlandskaja',
      post_seo: null,
    },
    {
      ID: '23',
      post: null,
      _NAME: 'Іспанська',
      SLUG: 'ispanskaja',
      post_seo: null,
    },
    {
      ID: '11',
      post: null,
      _NAME: 'Італійська',
      SLUG: 'italjanskaja',
      post_seo: null,
    },
    {
      ID: '12',
      post: null,
      _NAME: 'Кавказька',
      SLUG: 'kavkazkaja',
      post_seo: null,
    },
    {
      ID: '22',
      post: null,
      _NAME: 'Китайська',
      SLUG: 'kitajskaja',
      post_seo: null,
    },
    {
      ID: '20',
      post: null,
      _NAME: 'Кримська',
      SLUG: 'krumskaja',
      post_seo: null,
    },
    {
      ID: '27',
      post: null,
      _NAME: 'Кубинська',
      SLUG: 'kubinskaja',
      post_seo: null,
    },
    {
      ID: '26',
      post: null,
      _NAME: 'Латиноамериканська',
      SLUG: 'latinoamerykanskaja',
      post_seo: null,
    },
    {
      ID: '25',
      post: null,
      _NAME: 'Мексиканська',
      SLUG: 'meksikanskaja',
      post_seo: null,
    },
    {
      ID: '13',
      post: null,
      _NAME: 'Монгольська',
      SLUG: 'mongolskaja',
      post_seo: null,
    },
    {
      ID: '52',
      post: null,
      _NAME: 'Морепродукти',
      SLUG: 'seafood',
      post_seo: null,
    },
    {
      ID: '50',
      post: null,
      _NAME: 'Одеська',
      SLUG: 'odeska',
      post_seo: null,
    },
    {
      ID: '40',
      post: null,
      _NAME: 'Паназіатська',
      SLUG: 'panaziatskaja',
      post_seo: null,
    },
    {
      ID: '21',
      post: null,
      _NAME: 'Середземноморська',
      SLUG: 'sredizemnomorskaja',
      post_seo: null,
    },
    {
      ID: '47',
      post: null,
      _NAME: 'Суші, сашимі, ролли',
      SLUG: 'sushi-rolly',
      post_seo: null,
    },
    {
      ID: '33',
      post: null,
      _NAME: 'Східна',
      SLUG: 'vostocnaja',
      post_seo: null,
    },
    {
      ID: '14',
      post: null,
      _NAME: 'Тайська',
      SLUG: 'tajskaja',
      post_seo: null,
    },
    {
      ID: '37',
      post: null,
      _NAME: 'Турецька',
      SLUG: 'tureckaja',
      post_seo: null,
    },
    {
      ID: '42',
      post: null,
      _NAME: 'Угорська',
      SLUG: 'vengerskaja',
      post_seo: null,
    },
    {
      ID: '15',
      post: null,
      _NAME: 'Узбецька',
      SLUG: 'uzbeckaja',
      post_seo: null,
    },
    {
      ID: '16',
      post: null,
      _NAME: 'Українська',
      SLUG: 'ukrainskaja',
      post_seo: null,
    },
    {
      ID: '48',
      post: null,
      _NAME: 'Устриці',
      SLUG: 'ustritsy',
      post_seo: null,
    },
    {
      ID: '17',
      post: null,
      _NAME: 'Французька',
      SLUG: 'francuzkaja',
      post_seo: null,
    },
    {
      ID: '36',
      post: null,
      _NAME: 'Фьюжн',
      SLUG: 'fusion',
      post_seo: null,
    },
    {
      ID: '35',
      post: null,
      _NAME: 'Чеська',
      SLUG: 'czeskaja',
      post_seo: null,
    },
    {
      ID: '19',
      post: null,
      _NAME: 'Чорноморська',
      SLUG: 'czernomorskaja',
      post_seo: null,
    },
    {
      ID: '18',
      post: null,
      _NAME: 'Японська',
      SLUG: 'japonskaja',
      post_seo: null,
    },
  ],
  options: [
    {
      ID: '74',
      post_name: null,
      _NAME: null,
      NAME: 'Dj-пульт',
      SLUG: 'Dj-pult',
      post: null,
      post_seo: null,
    },
    {
      ID: '166',
      post_name: null,
      _NAME: null,
      NAME: 'Lobby bar',
      SLUG: 'lobby-bar',
      post: null,
      post_seo: null,
    },
    {
      ID: '32',
      post_name: null,
      _NAME: null,
      NAME: 'TV/Video',
      SLUG: 'TV-Video',
      post: null,
      post_seo: null,
    },
    {
      ID: '10',
      post_name: null,
      _NAME: null,
      NAME: 'VIP-зал',
      SLUG: 'VIP-zal',
      post: null,
      post_seo: null,
    },
    {
      ID: '1',
      post_name: null,
      _NAME: null,
      NAME: 'Wi-Fi',
      SLUG: 'Wi-Fi',
      post: null,
      post_seo: null,
    },
    {
      ID: '165',
      post_name: null,
      _NAME: null,
      NAME: 'Авторское Dinner Show',
      SLUG: 'avtorske-dinner-show',
      post: null,
      post_seo: null,
    },
    {
      ID: '42',
      post_name: null,
      _NAME: null,
      NAME: 'Аніматор на вихідних',
      SLUG: 'animator-po-vyhodnym',
      post: null,
      post_seo: null,
    },
    {
      ID: '4',
      post_name: null,
      _NAME: null,
      NAME: 'Бізнес-ланч',
      SLUG: 'biznes-lanch',
      post: null,
      post_seo: null,
    },
    {
      ID: '28',
      post_name: null,
      _NAME: null,
      NAME: 'Більярд',
      SLUG: 'bilyard',
      post: null,
      post_seo: null,
    },
    {
      ID: '82',
      post_name: null,
      _NAME: null,
      NAME: 'Біля води',
      SLUG: 'vozle-vody',
      post: null,
      post_seo: null,
    },
    {
      ID: '31',
      post_name: null,
      _NAME: null,
      NAME: 'Банкетний зал',
      SLUG: 'banketnyy-zal',
      post: null,
      post_seo: null,
    },
    {
      ID: '45',
      post_name: null,
      _NAME: null,
      NAME: 'Басейн',
      SLUG: 'basseyn',
      post: null,
      post_seo: null,
    },
    {
      ID: '56',
      post_name: null,
      _NAME: null,
      NAME: 'Блюда из дичи',
      SLUG: 'blyuda-iz-dichi',
      post: null,
      post_seo: null,
    },
    {
      ID: '81',
      post_name: null,
      _NAME: null,
      NAME: 'Блюда на открытом огне или в дровяной печи',
      SLUG: 'blyuda-na-otkrytom-ogne_v-drovyanoy-pechi',
      post: null,
      post_seo: null,
    },
    {
      ID: '106',
      post_name: null,
      _NAME: null,
      NAME: 'Блюда с собой',
      SLUG: 'blyuda-s-soboy',
      post: null,
      post_seo: null,
    },
    {
      ID: '111',
      post_name: null,
      _NAME: null,
      NAME: 'Бургери',
      SLUG: 'burgery',
      post: null,
      post_seo: null,
    },
    {
      ID: '52',
      post_name: null,
      _NAME: null,
      NAME: 'Винная карта',
      SLUG: 'vinnaya-karta',
      post: null,
      post_seo: null,
    },
    {
      ID: '162',
      post_name: null,
      _NAME: null,
      NAME: 'Гастрономічна крамниця',
      SLUG: 'gastronomicheskaya-lavka',
      post: null,
      post_seo: null,
    },
    {
      ID: '101',
      post_name: null,
      _NAME: null,
      NAME: 'Детская игровая площадка',
      SLUG: 'detskaya-igrovaya-ploschadka',
      post: null,
      post_seo: null,
    },
    {
      ID: '13',
      post_name: null,
      _NAME: null,
      NAME: 'Детская комната',
      SLUG: 'detskaya-komnata',
      post: null,
      post_seo: null,
    },
    {
      ID: '134',
      post_name: null,
      _NAME: null,
      NAME: 'Детские мастер-классы',
      SLUG: 'detskie-master-klassy',
      post: null,
      post_seo: null,
    },
    {
      ID: '91',
      post_name: null,
      _NAME: null,
      NAME: 'Детский стульчик',
      SLUG: 'detskiy-stulchik',
      post: null,
      post_seo: null,
    },
    {
      ID: '89',
      post_name: null,
      _NAME: null,
      NAME: 'Детское меню',
      SLUG: 'detskoe-menyu',
      post: null,
      post_seo: null,
    },
    {
      ID: '12',
      post_name: null,
      _NAME: null,
      NAME: 'Жива музика',
      SLUG: 'zhivaya-muzyka',
      post: null,
      post_seo: null,
    },
    {
      ID: '6',
      post_name: null,
      _NAME: null,
      NAME: 'Завтраки',
      SLUG: 'zavtraki',
      post: null,
      post_seo: null,
    },
    {
      ID: '84',
      post_name: null,
      _NAME: null,
      NAME: 'Зал с камином',
      SLUG: 'zal-s-kaminom',
      post: null,
      post_seo: null,
    },
    {
      ID: '70',
      post_name: null,
      _NAME: null,
      NAME: 'Засклена тераса',
      SLUG: 'zasteklennaya-terrasa',
      post: null,
      post_seo: null,
    },
    {
      ID: '8',
      post_name: null,
      _NAME: null,
      NAME: 'Кавова карта',
      SLUG: 'kofeynaya-karta',
      post: null,
      post_seo: null,
    },
    {
      ID: '3',
      post_name: null,
      _NAME: null,
      NAME: 'Кальян',
      SLUG: 'kalyan',
      post: null,
      post_seo: null,
    },
    {
      ID: '19',
      post_name: null,
      _NAME: null,
      NAME: 'Караоке',
      SLUG: 'karaoke',
      post: null,
      post_seo: null,
    },
    {
      ID: '54',
      post_name: null,
      _NAME: null,
      NAME: 'Коктейльна карта',
      SLUG: 'kokteylnaya-karta',
      post: null,
      post_seo: null,
    },
    {
      ID: '21',
      post_name: null,
      _NAME: null,
      NAME: 'Конференц-зал',
      SLUG: 'konferenc-zal',
      post: null,
      post_seo: null,
    },
    {
      ID: '103',
      post_name: null,
      _NAME: null,
      NAME: 'Концерти',
      SLUG: 'koncerty',
      post: null,
      post_seo: null,
    },
    {
      ID: '62',
      post_name: null,
      _NAME: null,
      NAME: 'Краби',
      SLUG: 'kraby',
      post: null,
      post_seo: null,
    },
    {
      ID: '15',
      post_name: null,
      _NAME: null,
      NAME: 'Літній майданчик / тераса',
      SLUG: 'letnyaya-ploschadka-terrasa',
      post: null,
      post_seo: null,
    },
    {
      ID: '167',
      post_name: null,
      _NAME: null,
      NAME: 'Ледник с морепродуктами',
      SLUG: 'lednik-s-moreproduktami',
      post: null,
      post_seo: null,
    },
    {
      ID: '161',
      post_name: null,
      _NAME: null,
      NAME: 'Моцарелла-бар',
      SLUG: 'mocarella-bar',
      post: null,
      post_seo: null,
    },
    {
      ID: '108',
      post_name: null,
      _NAME: null,
      NAME: 'Наливки і самогон власного приготування',
      SLUG: 'nalivki-i-samogon-sobstvennogo-prigotovleniya',
      post: null,
      post_seo: null,
    },
    {
      ID: '33',
      post_name: null,
      _NAME: null,
      NAME: 'Настільні ігри',
      SLUG: 'nastolnye-igry',
      post: null,
      post_seo: null,
    },
    {
      ID: '63',
      post_name: null,
      _NAME: null,
      NAME: 'Омари',
      SLUG: 'omary',
      post: null,
      post_seo: null,
    },
    {
      ID: '2',
      post_name: null,
      _NAME: null,
      NAME: 'Оплата кредиткой',
      SLUG: 'oplata-kreditkoy',
      post: null,
      post_seo: null,
    },
    {
      ID: '41',
      post_name: null,
      _NAME: null,
      NAME: 'Парковка',
      SLUG: 'parkovka',
      post: null,
      post_seo: null,
    },
    {
      ID: '110',
      post_name: null,
      _NAME: null,
      NAME: 'Пивоварня',
      SLUG: 'pivovarnya',
      post: null,
      post_seo: null,
    },
    {
      ID: '123',
      post_name: null,
      _NAME: null,
      NAME: 'Послуга cork-fee',
      SLUG: 'usluga-cork-fee',
      post: null,
      post_seo: null,
    },
    {
      ID: '75',
      post_name: null,
      _NAME: null,
      NAME: 'Проектор',
      SLUG: 'proektor',
      post: null,
      post_seo: null,
    },
    {
      ID: '80',
      post_name: null,
      _NAME: null,
      NAME: 'Рояль',
      SLUG: 'royal',
      post: null,
      post_seo: null,
    },
    {
      ID: '94',
      post_name: null,
      _NAME: null,
      NAME: 'Сауна',
      SLUG: 'sauna',
      post: null,
      post_seo: null,
    },
    {
      ID: '114',
      post_name: null,
      _NAME: null,
      NAME: 'Сигарна зала',
      SLUG: 'sigarnyy-zal',
      post: null,
      post_seo: null,
    },
    {
      ID: '73',
      post_name: null,
      _NAME: null,
      NAME: 'Сигарна карта',
      SLUG: 'sigarnaya-karta',
      post: null,
      post_seo: null,
    },
    {
      ID: '36',
      post_name: null,
      _NAME: null,
      NAME: 'Стейк-меню',
      SLUG: 'steyk-menyu',
      post: null,
      post_seo: null,
    },
    {
      ID: '130',
      post_name: null,
      _NAME: null,
      NAME: 'Стоянка яхт і катерів',
      SLUG: 'stoyanka-yaht-i-katerov',
      post: null,
      post_seo: null,
    },
    {
      ID: '38',
      post_name: null,
      _NAME: null,
      NAME: 'Суші',
      SLUG: 'sushi',
      post: null,
      post_seo: null,
    },
    {
      ID: '79',
      post_name: null,
      _NAME: null,
      NAME: 'Сцена',
      SLUG: 'scena',
      post: null,
      post_seo: null,
    },
    {
      ID: '127',
      post_name: null,
      _NAME: null,
      NAME: 'Счастливые часы',
      SLUG: 'schastlivye-chasy',
      post: null,
      post_seo: null,
    },
    {
      ID: '22',
      post_name: null,
      _NAME: null,
      NAME: 'Танцпол',
      SLUG: 'tancpol',
      post: null,
      post_seo: null,
    },
    {
      ID: '30',
      post_name: null,
      _NAME: null,
      NAME: 'Трансляція спортивних подій',
      SLUG: 'translyaciya-sportivnyh-sobytiy',
      post: null,
      post_seo: null,
    },
    {
      ID: '60',
      post_name: null,
      _NAME: null,
      NAME: 'Устриці',
      SLUG: 'ustricy',
      post: null,
      post_seo: null,
    },
    {
      ID: '9',
      post_name: null,
      _NAME: null,
      NAME: 'Чайна карта',
      SLUG: 'chaynaya-karta',
      post: null,
      post_seo: null,
    },
    {
      ID: '104',
      post_name: null,
      _NAME: null,
      NAME: 'Шезлонг',
      SLUG: 'shezlong',
      post: null,
      post_seo: null,
    },
  ],
  raion: [
    {
      ID: '1',
      post: null,
      CITY: '1',
      NAME: 'Голосіївський',
      SLUG: 'golosiivski',
      post_seo: null,
    },
    {
      ID: '2',
      post: null,
      CITY: '1',
      NAME: 'Дарницький',
      SLUG: 'darnitskii',
      post_seo: null,
    },
    {
      ID: '4',
      post: null,
      CITY: '1',
      NAME: 'Дніпровський',
      SLUG: 'dneprovskii',
      post_seo: null,
    },
    {
      ID: '5',
      post: null,
      CITY: '1',
      NAME: 'Оболонський',
      SLUG: 'obolonskii',
      post_seo: null,
    },
    {
      ID: '6',
      post: null,
      CITY: '1',
      NAME: 'Печерський',
      SLUG: 'pecerskii',
      post_seo: null,
    },
    {
      ID: '7',
      post: null,
      CITY: '1',
      NAME: 'Поділський',
      SLUG: 'podolskii',
      post_seo: null,
    },
    {
      ID: '8',
      post: null,
      CITY: '1',
      NAME: 'Святошинський',
      SLUG: 'sviatoshinskii',
      post_seo: null,
    },
    {
      ID: '9',
      post: null,
      CITY: '1',
      NAME: "Солом'янський",
      SLUG: 'solomenskii',
      post_seo: null,
    },
    {
      ID: '10',
      post: null,
      CITY: '1',
      NAME: 'Шевченківський',
      SLUG: 'shevchenkovskii',
      post_seo: null,
    },
  ],
  lines: [
    {
      STATUS: 'active',
      POSITION: '',
      ID: '1',
      NAME: 'Червона гілка',
      SHORT_NAME: 'Червона',
      SUBWAYS: [
        {
          ID: '34',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Академмістечко',
          SLUG: 'akademgorodok',
          post_seo: null,
        },
        {
          ID: '35',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Арсенальна',
          SLUG: 'arsenalnaya',
          post_seo: null,
        },
        {
          ID: '36',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Берестейська',
          SLUG: 'beresteyskaya',
          post_seo: null,
        },
        {
          ID: '37',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Вокзальна',
          SLUG: 'vokzalnaya',
          post_seo: null,
        },
        {
          ID: '38',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Гідропарк',
          SLUG: 'gidropark',
          post_seo: null,
        },
        {
          ID: '39',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Дарниця',
          SLUG: 'darnica',
          post_seo: null,
        },
        {
          ID: '40',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Дніпро',
          SLUG: 'dnepr',
          post_seo: null,
        },
        {
          ID: '41',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Житомирська',
          SLUG: 'zhitomirskaya',
          post_seo: null,
        },
        {
          ID: '43',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Лівобережна',
          SLUG: 'levoberezhnaya',
          post_seo: null,
        },
        {
          ID: '44',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Лісова',
          SLUG: 'lesnaya',
          post_seo: null,
        },
        {
          ID: '45',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Нивки',
          SLUG: 'nivki',
          post_seo: null,
        },
        {
          ID: '46',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Політехнічний інститут',
          SLUG: 'politehnicheskiy-institut',
          post_seo: null,
        },
        {
          ID: '47',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Святошин',
          SLUG: 'svyatoshin',
          post_seo: null,
        },
        {
          ID: '48',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Театральна',
          SLUG: 'teatralnaya',
          post_seo: null,
        },
        {
          ID: '49',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Університет',
          SLUG: 'universitet',
          post_seo: null,
        },
        {
          ID: '42',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Хрещатик',
          SLUG: 'kreschatik',
          post_seo: null,
        },
        {
          ID: '50',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Чернігівська',
          SLUG: 'chernigovskaya',
          post_seo: null,
        },
        {
          ID: '51',
          post: null,
          CITY: '1',
          LINE: '1',
          NAME: 'Шулявська',
          SLUG: 'shulyavskaya',
          post_seo: null,
        },
      ],
      STYLE: '',
    },
    {
      STATUS: '',
      POSITION: '',
      ID: '2',
      NAME: 'Зелена гілка',
      SHORT_NAME: 'Зелена',
      SUBWAYS: [
        {
          ID: '1',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Бориспільська',
          SLUG: 'borispolskaya',
          post_seo: null,
        },
        {
          ID: '2',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Видубичі',
          SLUG: 'vydubichi',
          post_seo: null,
        },
        {
          ID: '3',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Вирлиця',
          SLUG: 'vyrlica',
          post_seo: null,
        },
        {
          ID: '5',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Дорогожичі',
          SLUG: 'dorogozhichi',
          post_seo: null,
        },
        {
          ID: '6',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Дружби народів',
          SLUG: 'druzhby-narodov',
          post_seo: null,
        },
        {
          ID: '7',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Золоті ворота',
          SLUG: 'zolotye-vorota',
          post_seo: null,
        },
        {
          ID: '8',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Кловська',
          SLUG: 'klovskaya',
          post_seo: null,
        },
        {
          ID: '10',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: "Лук'янівська",
          SLUG: 'lukyanovskaya',
          post_seo: null,
        },
        {
          ID: '11',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Осокорки',
          SLUG: 'osokorki',
          post_seo: null,
        },
        {
          ID: '4',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Палац спорту',
          SLUG: 'dvorec-sporta',
          post_seo: null,
        },
        {
          ID: '12',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Печерська',
          SLUG: 'pecherskaya',
          post_seo: null,
        },
        {
          ID: '13',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Позняки',
          SLUG: 'poznyaki',
          post_seo: null,
        },
        {
          ID: '15',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Сирець',
          SLUG: 'syrec',
          post_seo: null,
        },
        {
          ID: '14',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Славутич',
          SLUG: 'slavutich',
          post_seo: null,
        },
        {
          ID: '16',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Харківська',
          SLUG: 'harkovskaya',
          post_seo: null,
        },
        {
          ID: '9',
          post: null,
          CITY: '1',
          LINE: '2',
          NAME: 'Червоний Хутір',
          SLUG: 'krasnyy-hutor',
          post_seo: null,
        },
      ],
    },
    {
      STATUS: '',
      POSITION: 'last',
      ID: '3',
      NAME: 'Синя гілка',
      SHORT_NAME: 'Синя',
      SUBWAYS: [
        {
          ID: '17',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Васильківська',
          SLUG: 'vasilkovskaya',
          post_seo: null,
        },
        {
          ID: '18',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Виставковий центр',
          SLUG: 'vystavochnyy-centr',
          post_seo: null,
        },
        {
          ID: '19',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Героїв Дніпра',
          SLUG: 'geroev-dnepra',
          post_seo: null,
        },
        {
          ID: '20',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Голосіївська',
          SLUG: 'goloseevskaya',
          post_seo: null,
        },
        {
          ID: '22',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Деміївська',
          SLUG: 'demeevskaya',
          post_seo: null,
        },
        {
          ID: '23',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Іподром',
          SLUG: 'ippodrom',
          post_seo: null,
        },
        {
          ID: '24',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Контрактова площа',
          SLUG: 'kontraktovaya-ploschad',
          post_seo: null,
        },
        {
          ID: '25',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Либідська',
          SLUG: 'lybedskaya',
          post_seo: null,
        },
        {
          ID: '26',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'М. Незалежності',
          SLUG: 'maydan-nezalezhnosti',
          post_seo: null,
        },
        {
          ID: '27',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Мінська',
          SLUG: 'minskaya',
          post_seo: null,
        },
        {
          ID: '28',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Оболонь',
          SLUG: 'obolon',
          post_seo: null,
        },
        {
          ID: '29',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Олімпійська',
          SLUG: 'olimpiyskaya',
          post_seo: null,
        },
        {
          ID: '21',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Палац Україна',
          SLUG: 'dvorec-ukraina',
          post_seo: null,
        },
        {
          ID: '31',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Пл. Льва Толстого',
          SLUG: 'ploschad-lva-tolstogo',
          post_seo: null,
        },
        {
          ID: '30',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Почайна',
          SLUG: 'petrovka',
          post_seo: null,
        },
        {
          ID: '32',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Поштова площа',
          SLUG: 'pochtovaya-ploschad',
          post_seo: null,
        },
        {
          ID: '33',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Тараса Шевченка',
          SLUG: 'tarasa-shevchenka',
          post_seo: null,
        },
        {
          ID: '58',
          post: null,
          CITY: '1',
          LINE: '3',
          NAME: 'Теремки',
          SLUG: 'teremki',
          post_seo: null,
        },
      ],
    },
  ],
};
