# Generated by Django 5.0.6 on 2024-05-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('city', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=155)),
                ('data_created', models.DateField()),
                ('medium_check', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Бар', 'Bar'), ('Ресторан', 'Restaurant'), ('Кафе', 'Cafe'), ('Паб', 'Pub'), ('Піцерія', 'Pizzeria')], default='Кафе', max_length=155)),
                ('сuisine', models.CharField(blank=True, choices=[('Японська', 'Japanese'), ('Італійська', 'Italian'), ('Французька', 'French'), ('Китайська', 'Chinese'), ('Індійська', 'Indian'), ('Мексиканська', 'Mexican'), ('Тайська', 'Thai'), ('Грецька', 'Greek'), ('Іспанська', 'Spanish'), ('Українська', 'Ukrainian')], max_length=155, null=True)),
                ('metro', models.CharField(blank=True, choices=[('Житомирська', 'Zhytomyrska'), ('Святошин', 'Sviatoshyno'), ('Нивки', 'Nyvky'), ('Берестейська', 'Beresteiska'), ('Шулявська', 'Shuliavska'), ('Вокзальна', 'Vokzalna'), ('Університет', 'Universytet'), ('Театральна', 'Teatralna'), ('Хрещатик', 'Khreshchatyk'), ('Арсенальна', 'Arsenalna'), ('Дніпро', 'Dnipro'), ('Гідропарк', 'Hidropark'), ('Лівобережна', 'Livoberezhna'), ('Дарниця', 'Darnytsia'), ('Чернігівська', 'Chernihivska'), ('Лісова', 'Lisova'), ('Оболонь', 'Obolon')], max_length=155, null=True)),
                ('main_photo', models.ImageField(default='uploads/main_photos/default.jpg', upload_to='uploads/main_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=155)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe_api.cafe')),
            ],
        ),
    ]
