# Generated by Django 5.0.6 on 2024-05-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0002_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe_api.cafe')),
            ],
        ),
    ]
