# Generated by Django 5.0.6 on 2024-05-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='features',
            field=models.ManyToManyField(blank=True, to='cafe_api.feature'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='cafe_api.cafe'),
        ),
    ]
