# Generated by Django 5.0.6 on 2024-05-14 14:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0004_cafe_features_alter_contact_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='type',
            field=models.CharField(choices=[('Бар', 'Bar'), ('Ресторан', 'Restaurant'), ('Кафе', 'Cafe'), ('Паб', 'Pub'), ('Піцерія', 'Pizzeria'), ('Пекарня', 'Bakery')], default='Кафе', max_length=155),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cafe_api.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe_api.review')),
            ],
        ),
    ]
