# Generated by Django 5.0.6 on 2024-05-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0006_metro_cafe_url_review_data_created_alter_cafe_metro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafes', to='cafe_api.metro'),
        ),
    ]
