# Generated by Django 5.0.6 on 2024-05-23 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0007_alter_cafe_metro'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfMetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='сuisine',
            new_name='cuisine',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='short_name',
        ),
        migrations.AddField(
            model_name='metro',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metroes', to='cafe_api.lineofmetro'),
            preserve_default=False,
        ),
    ]
