# Generated by Django 5.0.6 on 2024-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0008_lineofmetro_rename_сuisine_cafe_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('Japanese', 'Японська'), ('Italian', 'Італійська'), ('French', 'Французька'), ('Chinese', 'Китайська'), ('Indian', 'Індійська'), ('Mexican', 'Мексиканська'), ('Thai', 'Тайська'), ('Greek', 'Грецька'), ('Spanish', 'Іспанська'), ('Ukrainian', 'Українська')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='type',
            field=models.CharField(choices=[('Bar', 'Бар'), ('Restaurant', 'Ресторан'), ('Cafe', 'Кафе'), ('Pub', 'Паб'), ('Pizzeria', 'Піцерія'), ('Bakery', 'Пекарня')], default='Cafe', max_length=155),
        ),
    ]
