# Generated by Django 5.0.6 on 2024-06-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0011_alter_gallery_image_alter_reviewimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='cafe_api.cafe')),
            ],
        ),
    ]
