# Generated by Django 5.0.6 on 2024-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0012_cafe_phone_number_cafeworkinghours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-data_created']},
        ),
        migrations.AddField(
            model_name='cafe',
            name='google_address_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
