# Generated by Django 5.0.6 on 2024-06-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0012_cafeworkinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='phone_number',
            field=models.IntegerField(default=380111111111),
        ),
    ]
