# Generated by Django 5.0.6 on 2024-06-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0013_alter_review_options_cafe_google_address_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
