# Generated by Django 5.0.6 on 2024-06-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0014_alter_cafe_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='url',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='cafe',
            name='cafe_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
