# Generated by Django 5.0.6 on 2024-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0015_rename_url_cafe_slug_cafe_cafe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafe_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='google_address_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
