# Generated by Django 5.0.6 on 2024-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0016_alter_cafe_cafe_url_alter_cafe_google_address_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='google_address_url',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
